export const PLAYER_MAX_HP = 3;
export const PLAYER_INVULNERABILITY_SECONDS = 0.7;
export const PLAYER_DAMAGE_FLASH_SECONDS = 0.24;

export const ENEMY_PROJECTILE_DAMAGE = 1;
export const ENEMY_PROJECTILE_SPEED_CELLS_PER_SECOND = 3;
export const ENEMY_FIRE_COOLDOWN_SECONDS = 1.45;
export const ENEMY_FIRE_WINDUP_SECONDS = 0.6;
